"""Implements the feature tranformers of the VAEP framework."""

from typing import Callable

import numpy as np
import pandas as pd

import socceraction.atomic.features as fs
import socceraction.atomic.spadl as atomicspadl
from socceraction.features.utils import create_gamestate_features
from socceraction.types import Actions, Features, GameStates
from socceraction.utils import deprecated

FeatureTransfomer = Callable[..., Features]


def feature_column_names(fs: list[FeatureTransfomer], nb_prev_actions: int = 3) -> list[str]:
    """Return the names of the features generated by a list of transformers.

    Parameters
    ----------
    fs : list(callable)
        A list of feature transformers.
    nb_prev_actions : int, default=3  # noqa: DAR103
        The number of previous actions included in the game state.

    Returns
    -------
    list(str)
        The name of each generated feature.
    """
    spadlcolumns = [
        "game_id",
        "original_event_id",
        "action_id",
        "period_id",
        "time_seconds",
        "team_id",
        "player_id",
        "x",
        "y",
        "dx",
        "dy",
        "bodypart_id",
        "bodypart_name",
        "type_id",
        "type_name",
    ]
    dummy_actions = pd.DataFrame(np.zeros((10, len(spadlcolumns))), columns=spadlcolumns)
    for c in spadlcolumns:
        if "name" in c:
            dummy_actions[c] = dummy_actions[c].astype(str)
    gs = gamestates(dummy_actions, nb_prev_actions)  # type: ignore
    return list(pd.concat([f(gs) for f in fs], axis=1).columns)


def play_left_to_right(gamestates: GameStates, home_team_id: int) -> GameStates:
    """See socceraction.atomic_spadl.play_left_to_right."""
    return atomicspadl.utils.play_left_to_right(gamestates, home_team_id)


@deprecated("Use socceraction.atomic_spadl.to_gamestates instead.")
def gamestates(actions: Actions, nb_prev_actions: int = 3) -> GameStates:
    """See socceraction.atomic_spadl.to_gamestates."""
    return atomicspadl.utils.to_gamestates(actions, nb_prev_actions)


actiontype = create_gamestate_features(fs.actiontype)
actiontype_onehot = create_gamestate_features(fs.actiontype_onehot)
bodypart = create_gamestate_features(fs.bodypart)
bodypart_detailed = create_gamestate_features(fs.bodypart_detailed)
bodypart_onehot = create_gamestate_features(fs.bodypart_onehot)
bodypart_detailed_onehot = create_gamestate_features(fs.bodypart_detailed_onehot)
time = create_gamestate_features(fs.time)
player_possession_time = create_gamestate_features(fs.player_possession_time)
location = create_gamestate_features(fs.location)
polar = create_gamestate_features(fs.polar)
movement_polar = create_gamestate_features(fs.movement_polar)
direction = create_gamestate_features(fs.direction)
goalscore = create_gamestate_features(fs.goalscore)
speed = fs.speed
team = fs.team
time_delta = fs.time_delta


__all__ = [
    "feature_column_names",
    "play_left_to_right",
    "gamestates",
    "actiontype",
    "actiontype_onehot",
    "bodypart",
    "bodypart_detailed",
    "bodypart_onehot",
    "bodypart_detailed_onehot",
    "team",
    "time",
    "time_delta",
    "speed",
    "location",
    "polar",
    "movement_polar",
    "direction",
    "goalscore",
    "player_possession_time",
]
